[mypy]
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_configs = True
show_error_codes = True
pretty = True

[mypy-app.gui]
ignore_errors = True

[mypy-app.gui_guard]
ignore_errors = True

[mypy-app.gui_review]
ignore_errors = True

[mypy-app.layer_review]
ignore_errors = True

[mypy-app.circle_review]
ignore_errors = True

[mypy-app.gui_export]
ignore_errors = True
